<a href="https://colab.research.google.com/github/Nikhil-Tanwar/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.11.0+cu128'

## Introduction to Tensors

Creating Tensors

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
## Get tensor as Python int
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4307, 0.1515, 0.3103, 0.9763],
        [0.2544, 0.3109, 0.8977, 0.4250],
        [0.3163, 0.6025, 0.3795, 0.2892]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [20]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
### Default dtype
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [24]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
x = float_16_tensor * float_32_tensor
x.dtype

torch.float32

In [31]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5900, 0.7948, 0.0907, 0.7631],
        [0.1871, 0.0793, 0.2915, 0.8725],
        [0.4240, 0.8897, 0.3045, 0.2643]])

In [32]:
print(some_tensor.ndim)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

2
torch.Size([3, 4])
torch.float32
cpu


Change device - tensor.to("cuda")

In [33]:
a = torch.tensor([1, 2, 3])
b = a.clone()

In [34]:
a+10

tensor([11, 12, 13])

In [35]:
a-10

tensor([-9, -8, -7])

In [36]:
b*10

tensor([10, 20, 30])

In [37]:
b/10

tensor([0.1000, 0.2000, 0.3000])

In [38]:
a%2

tensor([1, 0, 1])

In [39]:
a*b

tensor([1, 4, 9])

In [40]:
torch.matmul(a,b)

tensor(14)

In [41]:
torch.matmul(a, b.reshape(1, -1).T)

tensor([14])

for timing - %%time

In [42]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

In [43]:
tensor_A.shape, tensor_A.ndim

(torch.Size([3, 2]), 2)

## Finding the min, max, mean, sum etc (Tensor Aggregation)

In [44]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [45]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [46]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [47]:
# torch.mean() requires float dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [48]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Arg gives index

In [49]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [50]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* dim 0 : Collapses rows : give one value per column
* dim 1 - Collapses columns - gives one value per row


* view is like reshape - but its reference rather than pass by value : z = x.view(9, 1)

In [51]:
x.reshape(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [52]:
x.unsqueeze(dim=0)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [53]:
x.squeeze(dim = 0)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

* vstack - stack as rows
* hstack - stack as columns

* hstack and vstack : stacks along existing dim
* stack creates a new dim

eg: torch(2,3)
* vstack - (4,3)
* stack (dim=0)- (2, 2, 3)

In [54]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [55]:
## Permute - returns 'view' of tensor with dims permuted. (rearranged)
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [56]:
torch.permute(x, (2, 0, 1)).shape

torch.Size([5, 2, 3])

* Rand - samples from uniform distribution, [0,1), Mean - 0.5, equal prob of being selected, Img Normalisation, Scaling, Random Dropouts prob
* Randn - samples from bell or Gaussian distribtion, (-inf,+inf), Mean - 0, std dev = 1, Weight Initialisation

In [57]:
x_original = torch.rand(224, 224, 3)
x_original.shape

torch.Size([224, 224, 3])

In [58]:
x_original = x_original.permute(2, 0 ,1)
x_original.shape

torch.Size([3, 224, 224])

* Default dtype of Numpy is float64
* Default dtype of Tensor is float32

In [59]:
# when converting from numpy to pytorch, pytorch reflects numpy default dtype (float64), unless specified
# changing the array, does not change tensor & vice versa
# Numpy to Tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [60]:
array.dtype, tensor.dtype, torch.arange(1.0, 8.0).dtype

(dtype('float64'), torch.float64, torch.float32)

In [61]:
# Tensor to Numpy array
tensor1 = torch.arange(1.0, 8.0)
array1 = tensor.numpy()
tensor1, array1

(tensor([1., 2., 3., 4., 5., 6., 7.]), array([1., 2., 3., 4., 5., 6., 7.]))

In [62]:
# Reproducibility - trying to reproduce randomness
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
t1 = torch.rand(size=(3,3))
torch.manual_seed(RANDOM_SEED)
t2 = torch.rand(size=(3,3))
t1, t2, t1 == t2

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

###Check for GPU access with PyTorch

using torch.cuda.is_available()

In [116]:
!nvidia-smi

Sat Jun 13 05:22:54 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   64C    P0             31W /   70W |     107MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [117]:
# Device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [118]:
torch.cuda.device_count()

1

##Putting tensors/models on GPU

In [123]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [124]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
# tensor_on_gpu = tensor.cuda()
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving Tensors back to CPU

In [126]:
# If tensor is on GPU, can't transform it into NumPy
#tensor_on_gpu.numpy()
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
#tensor_on_cpu = tensor_on_gpu.to("cpu").numpy()
tensor_on_cpu

array([1, 2, 3])

In [127]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')